# Generated by Django 4.0.1 on 2022-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_delivery_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='town_city',
        ),
        migrations.AddField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
