# Generated by Django 4.0.1 on 2022-03-07 07:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userbase_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='TW', max_length=2, verbose_name='country'),
        ),
    ]
