# Generated by Django 4.0.1 on 2022-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userbase_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='profile_img',
            field=models.ImageField(default='images/user_img/profile_default.jpg', upload_to='images/user_img'),
        ),
    ]
