# Generated by Django 4.0.1 on 2022-03-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_image_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
