# Generated by Django 4.0.1 on 2022-03-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='click_counter',
            field=models.IntegerField(default=0),
        ),
    ]
